/**
* This file was automatically generated by @abstract-money/ts-codegen@0.28.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @abstract-money/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {}
export type ExecuteMsg = {
  update_config: {};
};
export type QueryMsg = {
  config: {};
};
export type MigrateMsg = string;
export interface ConfigResponse {}
export type TemplateExecuteMsg = ExecuteMsg;