/**
* This file was automatically generated by cosmwasm-typescript-gen@0.3.9.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the cosmwasm-typescript-gen generate command to regenerate this file.
*/
import { CosmWasmClient, ExecuteResult, SigningCosmWasmClient } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
export declare type ExecuteMsg = {
    create_denom: {
        subdenom: string;
        [k: string]: unknown;
    };
};
export interface InstantiateMsg {
    [k: string]: unknown;
}
export declare type QueryMsg = string;
export interface TokenfactoryReadOnlyInterface {
    contractAddress: string;
}
export declare class TokenfactoryQueryClient implements TokenfactoryReadOnlyInterface {
    client: CosmWasmClient;
    contractAddress: string;
    constructor(client: CosmWasmClient, contractAddress: string);
}
export interface TokenfactoryInterface extends TokenfactoryReadOnlyInterface {
    contractAddress: string;
    sender: string;
    createDenom: ({ subdenom }: {
        subdenom: string;
    }, fee?: number | StdFee | "auto", memo?: string, funds?: readonly Coin[]) => Promise<ExecuteResult>;
}
export declare class TokenfactoryClient extends TokenfactoryQueryClient implements TokenfactoryInterface {
    client: SigningCosmWasmClient;
    sender: string;
    contractAddress: string;
    constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string);
    createDenom: ({ subdenom }: {
        subdenom: string;
    }, fee?: number | StdFee | "auto", memo?: string, funds?: readonly Coin[]) => Promise<ExecuteResult>;
}
//# sourceMappingURL=TokenfactoryContract.d.ts.map