/**
* This file was automatically generated by @abstract-money/ts-codegen@0.28.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @abstract-money/ts-codegen generate command to regenerate this file.
*/

export interface AdminResponse {
  admin?: string | null;
}
export type Addr = string;
export interface ConfigResponse {
  ans_host_address: Addr;
  manager_address: Addr;
  proxy_address: Addr;
}
export type ExecuteMsg = {
  base: BaseExecuteMsg;
} | {
  module: TemplateExecuteMsg;
} | {
  ibc_callback: IbcResponseMsg;
} | {
  receive: Cw20ReceiveMsg;
};
export type BaseExecuteMsg = {
  update_config: {
    ans_host_address?: string | null;
  };
};
export type TemplateExecuteMsg = {
  update_config: {};
};
export type StdAck = {
  result: Binary;
} | {
  error: string;
};
export type Binary = string;
export type Uint128 = string;
export interface IbcResponseMsg {
  id: string;
  msg: StdAck;
}
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg: Binary;
  sender: string;
}
export interface InstantiateMsg {
  base: BaseInstantiateMsg;
  module: TemplateInstantiateMsg;
}
export interface BaseInstantiateMsg {
  ans_host_address: string;
}
export interface TemplateInstantiateMsg {}
export type TemplateMigrateMsg = string;
export interface MigrateMsg {
  base: BaseMigrateMsg;
  module: TemplateMigrateMsg;
}
export interface BaseMigrateMsg {}
export type QueryMsg = {
  base: BaseQueryMsg;
} | {
  module: TemplateQueryMsg;
};
export type BaseQueryMsg = {
  config: {};
} | {
  admin: {};
};
export type TemplateQueryMsg = {
  config: {};
};
export type TemplateExecuteMsg = ExecuteMsg;