/**
* This file was automatically generated by @abstract-money/ts-codegen@0.28.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @abstract-money/ts-codegen generate command to regenerate this file.
*/

import { AdminResponse, Addr, ConfigResponse, ExecuteMsg, BaseExecuteMsg, TemplateExecuteMsg, StdAck, Binary, Uint128, IbcResponseMsg, Cw20ReceiveMsg, InstantiateMsg, BaseInstantiateMsg, TemplateInstantiateMsg, TemplateMigrateMsg, MigrateMsg, BaseMigrateMsg, QueryMsg, BaseQueryMsg, TemplateQueryMsg } from "./Template.types";
import { CamelCasedProperties } from "type-fest";
export abstract class TemplateExecuteMsgBuilder {
  static base = (baseExecuteMsg: BaseExecuteMsg): ExecuteMsg => {
    return {
      base: baseExecuteMsg
    };
  };
  static module = (templateExecuteMsg: TemplateExecuteMsg): ExecuteMsg => {
    return {
      module: templateExecuteMsg
    };
  };
  static ibcCallback = ({
    id,
    msg
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    ibc_callback: unknown;
  }>["ibc_callback"]>): ExecuteMsg => {
    return {
      ibc_callback: ({
        id,
        msg
      } as const)
    };
  };
  static receive = ({
    amount,
    msg,
    sender
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    receive: unknown;
  }>["receive"]>): ExecuteMsg => {
    return {
      receive: ({
        amount,
        msg,
        sender
      } as const)
    };
  };
}
export abstract class TemplateQueryMsgBuilder {
  static base = (baseQueryMsg: BaseQueryMsg): QueryMsg => {
    return {
      base: baseQueryMsg
    };
  };
  static module = (templateQueryMsg: TemplateQueryMsg): QueryMsg => {
    return {
      module: templateQueryMsg
    };
  };
}