/**
* This file was automatically generated by @abstract-money/ts-codegen@0.28.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @abstract-money/ts-codegen generate command to regenerate this file.
*/

export type AssetEntry = string;
export interface InstantiateMsg {
  desired_asset?: AssetEntry | null;
  exchanges: string[];
}
export type ExecuteMsg = {
  tip: {};
} | {
  update_config: {
    exchanges?: string[] | null | undefined;
  };
};
export type QueryMsg = {
  config: {};
} | {
  tipper: {
    address: string;
  };
} | {
  tip_count: {};
} | {
  list_tippers: {
    limit?: number | null | undefined;
    start_after?: string | null | undefined;
  };
};
export type MigrateMsg = string;
export interface ConfigResponse {
  desired_asset?: AssetEntry | null;
  exchanges: string[];
}
export type Addr = string;
export type Uint128 = string;
export interface TippersResponse {
  tippers: TipperResponse[];
}
export interface TipperResponse {
  address: Addr;
  count: number;
  total_amount: Uint128;
}
export interface TipCountResponse {
  count: number;
}
export type TemplateExecuteMsg = ExecuteMsg;